<?php
/**
 * SiteResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Waitlisted
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Waitlisted API
 *
 * Waitlisted API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Waitlisted;

/**
 * SiteResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description SiteResponse
/**
 * @package     Waitlisted
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SiteResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SiteResponse"
     */
    public function testSiteResponse()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "brand_color"
     */
    public function testPropertyBrandColor()
    {

    }

    /**
     * Test attribute "button_text_color"
     */
    public function testPropertyButtonTextColor()
    {

    }

    /**
     * Test attribute "custom_styles"
     */
    public function testPropertyCustomStyles()
    {

    }

    /**
     * Test attribute "ask_name"
     */
    public function testPropertyAskName()
    {

    }

    /**
     * Test attribute "signup_title"
     */
    public function testPropertySignupTitle()
    {

    }

    /**
     * Test attribute "signup_copy"
     */
    public function testPropertySignupCopy()
    {

    }

    /**
     * Test attribute "position_title"
     */
    public function testPropertyPositionTitle()
    {

    }

    /**
     * Test attribute "social_copy"
     */
    public function testPropertySocialCopy()
    {

    }

    /**
     * Test attribute "social_message"
     */
    public function testPropertySocialMessage()
    {

    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {

    }

    /**
     * Test attribute "share_social_copy"
     */
    public function testPropertyShareSocialCopy()
    {

    }

    /**
     * Test attribute "referral_copy"
     */
    public function testPropertyReferralCopy()
    {

    }

    /**
     * Test attribute "check_position_copy"
     */
    public function testPropertyCheckPositionCopy()
    {

    }

    /**
     * Test attribute "join_button_copy"
     */
    public function testPropertyJoinButtonCopy()
    {

    }

    /**
     * Test attribute "check_reservation_copy"
     */
    public function testPropertyCheckReservationCopy()
    {

    }

    /**
     * Test attribute "email_field_label"
     */
    public function testPropertyEmailFieldLabel()
    {

    }

    /**
     * Test attribute "name_field_label"
     */
    public function testPropertyNameFieldLabel()
    {

    }

    /**
     * Test attribute "thank_you_share_template"
     */
    public function testPropertyThankYouShareTemplate()
    {

    }

    /**
     * Test attribute "waitlist_threshold"
     */
    public function testPropertyWaitlistThreshold()
    {

    }

    /**
     * Test attribute "use_custom_thank_you"
     */
    public function testPropertyUseCustomThankYou()
    {

    }

    /**
     * Test attribute "hide_waitlist"
     */
    public function testPropertyHideWaitlist()
    {

    }

    /**
     * Test attribute "unmet_shared_template"
     */
    public function testPropertyUnmetSharedTemplate()
    {

    }

    /**
     * Test attribute "threshold_met"
     */
    public function testPropertyThresholdMet()
    {

    }

    /**
     * Test attribute "website_url"
     */
    public function testPropertyWebsiteUrl()
    {

    }

    /**
     * Test attribute "tracking_code"
     */
    public function testPropertyTrackingCode()
    {

    }

    /**
     * Test attribute "custom_css"
     */
    public function testPropertyCustomCss()
    {

    }

    /**
     * Test attribute "hide_branding"
     */
    public function testPropertyHideBranding()
    {

    }

    /**
     * Test attribute "total_count"
     */
    public function testPropertyTotalCount()
    {

    }

}
